//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        public int Id_Acceso { get; set; }
        public Nullable<int> Id_Personal { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public Nullable<System.DateTime> Fecha_ini { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
