//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignaZona
    {
        public int Id_asigna { get; set; }
        public Nullable<int> IdZona { get; set; }
        public Nullable<int> Id_personal { get; set; }
        public Nullable<System.DateTime> Fecha_asigna { get; set; }
        public Nullable<int> usuario { get; set; }
    }
}
