//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int Id_cliente { get; set; }
        public Nullable<int> IdMercado { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> IdDenominacion { get; set; }
        public string Califica { get; set; }
        public string RUC { get; set; }
        public string Direccion { get; set; }
        public string UbigeoComercial { get; set; }
        public string ReferenciaComercial { get; set; }
        public string TelefonoComercial { get; set; }
        public string NombrePropietario { get; set; }
        public string Domicilio { get; set; }
        public string UbigeoDomicilio { get; set; }
        public string ReferenciaDomicilio { get; set; }
        public string DNI { get; set; }
        public string TelefonoDomicilio { get; set; }
        public Nullable<int> GarantiaCred { get; set; }
        public Nullable<int> CreditoMaximo { get; set; }
        public string Observacion { get; set; }
        public string NumeroPuesto { get; set; }
    }
}
