//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int Id_Dcmto { get; set; }
        public Nullable<int> Ingreso_Salida { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> NroPagos { get; set; }
        public Nullable<int> NroDias { get; set; }
        public string FechaUltimoPago { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
