//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles
    {
        public int Id_Encab { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> Id_prod { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public Nullable<int> Medida { get; set; }
        public Nullable<decimal> CantidadKilos { get; set; }
        public Nullable<int> Id_UMedida { get; set; }
        public Nullable<double> PrecioUnit { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IGV { get; set; }
    }
}
