//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encabezado
    {
        public int Id_Encab { get; set; }
        public Nullable<int> Id_cliente { get; set; }
        public Nullable<int> Id_Docmto { get; set; }
        public Nullable<int> Num_Docmto { get; set; }
        public Nullable<int> Fecha_Docmto { get; set; }
        public Nullable<int> Id_FormaPago { get; set; }
        public string fechaCheque { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
        public Nullable<int> Id_TipoMov { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public string Estado_Docmto { get; set; }
        public string Estado_Pago { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public Nullable<decimal> TotalPrecio { get; set; }
        public Nullable<decimal> Tipo_Cambio { get; set; }
        public string Notas { get; set; }
        public Nullable<int> Id_Acceso { get; set; }
    }
}
