//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercados
    {
        public int IdMercado { get; set; }
        public int IdZona { get; set; }
        public string NombreCorto { get; set; }
        public string NombreLargo { get; set; }
        public string Direccion { get; set; }
        public string ubigeo { get; set; }
        public string Observ { get; set; }
    
        public virtual zonas zonas { get; set; }
    }
}
