//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Accesos = new HashSet<Accesos>();
        }
    
        public int Id_personal { get; set; }
        public string ApellidoPat { get; set; }
        public string ApellidoMat { get; set; }
        public string Nombres { get; set; }
        public string NroDNI { get; set; }
        public string Domicilio { get; set; }
        public string Ubigeo { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string CodCargo { get; set; }
        public string EstadoCivil { get; set; }
        public string Nrolpss { get; set; }
        public string NroHijos { get; set; }
        public string Observ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesos> Accesos { get; set; }
    }
}
