//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBIGEO
    {
        public string UBIGEO1 { get; set; }
        public string DISTRITO { get; set; }
        public string PROVINCIA { get; set; }
        public string DEPARTAM { get; set; }
        public string cod_dpto { get; set; }
    }
}
