//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AcEn
    {
        public int Id_Acceso { get; set; }
        public string Nombres { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public int Id_Encab { get; set; }
        public string NombreRSocial { get; set; }
        public string Nombre { get; set; }
        public string fechaCheque { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public string CodNom { get; set; }
    }
}
