//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AsignaZona
    {
        public Nullable<int> Id_personal { get; set; }
        public string NombreZona { get; set; }
        public int IdZona { get; set; }
        public string Nombres { get; set; }
        public int Id_asigna { get; set; }
        public string DescripCorta { get; set; }
        public string ApellidoMat { get; set; }
        public string ApellidoPat { get; set; }
    }
}
