//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Clientes
    {
        public int IdCliente { get; set; }
        public string Desc_Corta { get; set; }
        public string NroDocmto { get; set; }
        public string Califica { get; set; }
        public string NombreRSocial { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Ubigeo { get; set; }
        public string Referencia { get; set; }
        public string Telefono { get; set; }
        public string NombreCorto { get; set; }
        public string DescripCorta { get; set; }
        public string Codigo { get; set; }
        public int IdMercado { get; set; }
        public int IdClaseClie { get; set; }
        public int Id_DIdent { get; set; }
        public string DiMer { get; set; }
        public string zonmer { get; set; }
        public string NumeroPuesto { get; set; }
        public Nullable<int> Id_Acceso_crea { get; set; }
    }
}
