//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ComboClientes
    {
        public int Id_cliente { get; set; }
        public string NombrePropietario { get; set; }
        public string Codigo { get; set; }
        public int IdMercado { get; set; }
    }
}
