//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Encab
    {
        public int Id_Encab { get; set; }
        public string NombreRSocial { get; set; }
        public string Desc_Corta { get; set; }
        public Nullable<int> Num_Docmto { get; set; }
        public string fechaCheque { get; set; }
        public string NomFormaPago { get; set; }
        public string NomTipoMov { get; set; }
        public string Desc_Large { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public Nullable<decimal> tipocambio { get; set; }
        public string Direccion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantidadKilos { get; set; }
        public Nullable<double> PrecioUnit { get; set; }
        public string Descrip { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<int> Id_Ecab { get; set; }
        public Nullable<int> Id_Acceso { get; set; }
    }
}
