//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_EncabDet
    {
        public int Id_Encab { get; set; }
        public Nullable<int> Id_prod { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public Nullable<decimal> CantidadKilos { get; set; }
        public Nullable<double> PrecioUnit { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> Id_cliente { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public string fechaCheque { get; set; }
        public int IdMercado { get; set; }
        public string NombrePropietario { get; set; }
        public string NumeroPuesto { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<int> Id_FormaPago { get; set; }
        public string CodCompuesto { get; set; }
    }
}
