//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ListarPedidoFecha
    {
        public int Id_Encab { get; set; }
        public string fechaCheque { get; set; }
        public string CodNom { get; set; }
        public Nullable<decimal> Total_Venta { get; set; }
        public string Desc_Large { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
    }
}
