//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ListarProductos
    {
        public int Id_prod { get; set; }
        public string Nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> PesoKilos { get; set; }
        public Nullable<decimal> PVentaS { get; set; }
        public Nullable<decimal> PVentaD { get; set; }
    }
}
