//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Per
    {
        public int Id_personal { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public string NroDNI { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string Nombre { get; set; }
        public string EstadoCivil { get; set; }
        public string Nrolpss { get; set; }
        public string NroHijos { get; set; }
        public int Codigo { get; set; }
    }
}
