//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Pro
    {
        public int Id_Producto { get; set; }
        public Nullable<int> Valor { get; set; }
        public string Descrip { get; set; }
        public string Descripcion { get; set; }
        public string Simbolo { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Desc_Large { get; set; }
        public Nullable<decimal> PCompraS { get; set; }
        public Nullable<decimal> PCompraD { get; set; }
        public Nullable<decimal> PVentaS { get; set; }
        public Nullable<decimal> PVentaD { get; set; }
        public Nullable<decimal> StockMax { get; set; }
        public Nullable<decimal> StockMin { get; set; }
        public Nullable<decimal> StockAct { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Id_Umedida { get; set; }
        public string codde { get; set; }
        public Nullable<int> Id_Familia { get; set; }
    }
}
